### PR TITLE
Use GET parameters as fallback for missing BasicAuth header during update

### LINKED ISSUE #26: Updates through web browser show bad auth
If you update a hostname through URL

https://{user}:{pass}@dyn.c4fd.org/nic/update?hostname=blafoo.dyn.c4fd.org&myip=1.2.3.4

returns with bad auth error

### PR DESCRIPTION
**Pull request by fooker**
Fixes #26.

### CODE REVIEW

**Comment by indigo423** [comment]
All these changes just related to "Use GET parameters as fallback for missing BasicAuth header during update" ?!

**Comment by fooker** [comment]
This is due to consecutive changes. This branch is based on another outstanding pull request. The relevant changes can be found in the last commit.

**Comment by indigo423** [comment]
You should reconsider your pull request strategy and split them in the way your pull requests reflects the consecutive changes and make them reviewable.

**Comment by reissmann** [comment]
Merged into 0.3-dev

**Comment by fooker** [comment]
AFAIk there is no other way to handle pull request based on each other - the later pull request become smaller as the former pull requests get merged.

**Comment by indigo423** [comment]
There is .... always

**Comment by fooker** [comment]
Enlighten me with your great wisdom

**Comment by indigo423** [comment]
Turn back time, split pull requests and replay them in the right order.

**Comment by fooker** [comment]
What I've done in detail:


git checkout master

# Start work on issue 1
git branch issue/1
git checkout issue/1
# Edit some files
git commit -a -m "Fixed issue #1"
git push origin issue/1
# Create pull request for issue/1 against master

# Start work on issue 2
git branch issue/2
git checkout issue/2
# Edit some files
git commit -a -m "Fixed issue #2"
git push origin issue/2
# Create pull request for issue/2 against master


As you can see, the branch issue/2 is based on issue/1. After doing a pull request against master it contains all the commit from issue/1 and issue/2. To show only the commits from issue/2 the pull request must be done against issue/1 which even more wrong.

As sone as the pull request for issue/1 is merged into master, the commits from issue/1 will disapear from the pull request for issue/2 - which makes it reviewable again.

In my point of view, the branches are as small as possible and the pull request are in the correct order.

If there is anything I can do better, please give me a detailed example.

**Comment by indigo423** [comment]
You imply issue/1 is perfect without an review.

**Comment by reissmann** [comment]
Maybe we could discuss general participation rules somewhere else than inside a specific issue?

The one thing, which is badly wrong here is, the pull requests being issued against master instead of the next release branch (which did not yet exist on github at the time the pull requests were issued - so this was my fault).

**Comment by fooker** [comment]
@reissmann you are right. Time for an ddserver specific mailing list?

@indigo423 i don't imply there are perfect. If the need to be changed, the changes has to be done in the former branch (issue/1) and the pull request gets updated. The changes also needs to be merged in all later branches and will also be reflected in the according pull request.

**Pull request closed without merging**
